/*
 * Generated by Bluespec Compiler, version 2023.01 (build 52adafa5)
 * 
 * On Wed Sep  6 08:43:34 UTC 2023
 * 
 */
#include "bluesim_primitives.h"
#include "mkTbRCA.h"
#include "imported_BDPI_functions.h"


/* String declarations */
static std::string const __str_literal_2("FAILED %d + %d gave %d instead of %d", 36u);
static std::string const __str_literal_1("PASSED", 6u);


/* Constructor */
MOD_mkTbRCA::MOD_mkTbRCA(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_cycle(simHdl, "cycle", this, 32u, 0u, (tUInt8)0u),
    INST_randomVal1_ignore(simHdl, "randomVal1_ignore", this, 8u, (tUInt8)0u),
    INST_randomVal1_initialized(simHdl, "randomVal1_initialized", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_randomVal1_zaz(simHdl, "randomVal1_zaz", this, 8u, (tUInt8)0u),
    INST_randomVal2_ignore(simHdl, "randomVal2_ignore", this, 8u, (tUInt8)0u),
    INST_randomVal2_initialized(simHdl, "randomVal2_initialized", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_randomVal2_zaz(simHdl, "randomVal2_zaz", this, 8u, (tUInt8)0u),
    PORT_RST_N((tUInt8)1u),
    DEF_v__h691(2863311530u),
    DEF_v__h315(2863311530u)
{
  symbol_count = 13u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkTbRCA::init_symbols_0()
{
  init_symbol(&symbols[0u], "cycle", SYM_MODULE, &INST_cycle);
  init_symbol(&symbols[1u], "RL_randomVal1_every", SYM_RULE);
  init_symbol(&symbols[2u], "RL_randomVal1_every_1", SYM_RULE);
  init_symbol(&symbols[3u], "RL_randomVal2_every", SYM_RULE);
  init_symbol(&symbols[4u], "RL_randomVal2_every_1", SYM_RULE);
  init_symbol(&symbols[5u], "RL_test", SYM_RULE);
  init_symbol(&symbols[6u], "randomVal1_ignore", SYM_MODULE, &INST_randomVal1_ignore);
  init_symbol(&symbols[7u], "randomVal1_initialized", SYM_MODULE, &INST_randomVal1_initialized);
  init_symbol(&symbols[8u], "randomVal1_zaz", SYM_MODULE, &INST_randomVal1_zaz);
  init_symbol(&symbols[9u], "randomVal2_ignore", SYM_MODULE, &INST_randomVal2_ignore);
  init_symbol(&symbols[10u], "randomVal2_initialized", SYM_MODULE, &INST_randomVal2_initialized);
  init_symbol(&symbols[11u], "randomVal2_zaz", SYM_MODULE, &INST_randomVal2_zaz);
  init_symbol(&symbols[12u], "x__h945", SYM_DEF, &DEF_x__h945, 32u);
}


/* Rule actions */

void MOD_mkTbRCA::RL_randomVal1_every()
{
  tUInt8 DEF_new_value__h357;
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h315 = rand32();
  DEF_new_value__h357 = (tUInt8)((tUInt8)255u & DEF_v__h315);
  INST_randomVal1_zaz.METH_wset(DEF_new_value__h357);
}

void MOD_mkTbRCA::RL_randomVal1_every_1()
{
  DEF_x_wget__h250 = INST_randomVal1_zaz.METH_wget();
  DEF_v__h389 = INST_randomVal1_zaz.METH_whas() ? DEF_x_wget__h250 : (tUInt8)0u;
  INST_randomVal1_ignore.METH_wset(DEF_v__h389);
}

void MOD_mkTbRCA::RL_randomVal2_every()
{
  tUInt8 DEF_new_value__h733;
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h691 = rand32();
  DEF_new_value__h733 = (tUInt8)((tUInt8)255u & DEF_v__h691);
  INST_randomVal2_zaz.METH_wset(DEF_new_value__h733);
}

void MOD_mkTbRCA::RL_randomVal2_every_1()
{
  DEF_x_wget__h634 = INST_randomVal2_zaz.METH_wget();
  DEF_v__h764 = INST_randomVal2_zaz.METH_whas() ? DEF_x_wget__h634 : (tUInt8)0u;
  INST_randomVal2_ignore.METH_wset(DEF_v__h764);
}

void MOD_mkTbRCA::RL_test()
{
  tUInt8 DEF_high__h1138;
  tUInt32 DEF_x__h3376;
  tUInt8 DEF_y__h2126;
  tUInt8 DEF_x__h2125;
  tUInt8 DEF_y__h1908;
  tUInt8 DEF_y__h1694;
  tUInt8 DEF_x__h1693;
  tUInt8 DEF_y__h1692;
  tUInt8 DEF_x__h1691;
  tUInt8 DEF_y__h1910;
  tUInt8 DEF_x__h1909;
  tUInt8 DEF_x__h1907;
  tUInt8 DEF_y__h2124;
  tUInt8 DEF_x__h2123;
  tUInt8 DEF_y__h2341;
  tUInt8 DEF_y__h2339;
  tUInt8 DEF_x__h2338;
  tUInt8 DEF_y__h2595;
  tUInt8 DEF_x__h2594;
  tUInt8 DEF_y__h2593;
  tUInt8 DEF_x__h2592;
  tUInt8 DEF_y__h2811;
  tUInt8 DEF_x__h2810;
  tUInt8 DEF_y__h2809;
  tUInt8 DEF_x__h2808;
  tUInt8 DEF_y__h3027;
  tUInt8 DEF_x__h3026;
  tUInt8 DEF_y__h3025;
  tUInt8 DEF_x__h3024;
  tUInt8 DEF_c__h3122;
  tUInt8 DEF_x__h3133;
  tUInt8 DEF_c__h2907;
  tUInt8 DEF_x__h2918;
  tUInt8 DEF_c__h2691;
  tUInt8 DEF_x__h2702;
  tUInt8 DEF_c0__h1143;
  tUInt8 DEF_x__h2487;
  tUInt8 DEF_c__h2221;
  tUInt8 DEF_x__h2232;
  tUInt8 DEF_c__h2006;
  tUInt8 DEF_x__h2017;
  tUInt8 DEF_c__h1790;
  tUInt8 DEF_x__h1801;
  tUInt8 DEF_NOT_cycle_5_EQ_0_6_1_AND_NOT_cycle_5_EQ_128_7__ETC___d100;
  tUInt32 DEF_realAns__h3247;
  tUInt8 DEF_b__h1423;
  tUInt8 DEF_b__h1679;
  tUInt8 DEF_b__h1895;
  tUInt8 DEF_b__h2111;
  tUInt8 DEF_b__h2326;
  tUInt8 DEF_b__h2580;
  tUInt8 DEF_b__h2796;
  tUInt8 DEF_b__h3012;
  tUInt8 DEF_a__h1422;
  tUInt8 DEF_a__h1678;
  tUInt8 DEF_a__h1894;
  tUInt8 DEF_a__h2110;
  tUInt8 DEF_a__h2325;
  tUInt8 DEF_a__h2579;
  tUInt8 DEF_a__h2795;
  tUInt8 DEF_a__h3011;
  tUInt8 DEF_x__h2340;
  tUInt32 DEF_v__h1133;
  DEF_x__h945 = INST_cycle.METH_read();
  DEF_x_wget__h634 = INST_randomVal2_zaz.METH_wget();
  DEF_x_wget__h250 = INST_randomVal1_zaz.METH_wget();
  DEF_v__h389 = INST_randomVal1_zaz.METH_whas() ? DEF_x_wget__h250 : (tUInt8)0u;
  DEF_v__h764 = INST_randomVal2_zaz.METH_whas() ? DEF_x_wget__h634 : (tUInt8)0u;
  DEF_cycle_5_EQ_128___d17 = DEF_x__h945 == 128u;
  DEF_cycle_5_EQ_0___d16 = DEF_x__h945 == 0u;
  DEF_a__h3011 = (tUInt8)(DEF_v__h389 >> 7u);
  DEF_a__h2795 = (tUInt8)((tUInt8)1u & (DEF_v__h389 >> 6u));
  DEF_a__h2579 = (tUInt8)((tUInt8)1u & (DEF_v__h389 >> 5u));
  DEF_a__h2325 = (tUInt8)((tUInt8)1u & (DEF_v__h389 >> 4u));
  DEF_a__h2110 = (tUInt8)((tUInt8)1u & (DEF_v__h389 >> 3u));
  DEF_a__h1894 = (tUInt8)((tUInt8)1u & (DEF_v__h389 >> 2u));
  DEF_b__h3012 = (tUInt8)(DEF_v__h764 >> 7u);
  DEF_a__h1678 = (tUInt8)((tUInt8)1u & (DEF_v__h389 >> 1u));
  DEF_b__h2796 = (tUInt8)((tUInt8)1u & (DEF_v__h764 >> 6u));
  DEF_a__h1422 = (tUInt8)((tUInt8)1u & DEF_v__h389);
  DEF_b__h2580 = (tUInt8)((tUInt8)1u & (DEF_v__h764 >> 5u));
  DEF_b__h2326 = (tUInt8)((tUInt8)1u & (DEF_v__h764 >> 4u));
  DEF_x__h2340 = DEF_a__h2325 & DEF_b__h2326;
  DEF_b__h2111 = (tUInt8)((tUInt8)1u & (DEF_v__h764 >> 3u));
  DEF_b__h1679 = (tUInt8)((tUInt8)1u & (DEF_v__h764 >> 1u));
  DEF_b__h1895 = (tUInt8)((tUInt8)1u & (DEF_v__h764 >> 2u));
  DEF_b__h1423 = (tUInt8)((tUInt8)1u & DEF_v__h764);
  DEF_realAns__h3247 = 511u & ((511u & ((((tUInt32)((tUInt8)0u)) << 8u) | (tUInt32)(DEF_v__h389))) + (511u & ((((tUInt32)((tUInt8)0u)) << 8u) | (tUInt32)(DEF_v__h764))));
  DEF_x__h1801 = DEF_a__h1678 ^ DEF_b__h1679;
  DEF_c__h1790 = DEF_a__h1422 & DEF_b__h1423;
  DEF_x__h2017 = DEF_a__h1894 ^ DEF_b__h1895;
  DEF_x__h2232 = DEF_a__h2110 ^ DEF_b__h2111;
  DEF_x__h2702 = DEF_a__h2579 ^ DEF_b__h2580;
  DEF_x__h2487 = DEF_a__h2325 ^ DEF_b__h2326;
  DEF_x__h2918 = DEF_a__h2795 ^ DEF_b__h2796;
  DEF_x__h3133 = DEF_a__h3011 ^ DEF_b__h3012;
  DEF_x__h3026 = DEF_a__h3011 & DEF_b__h3012;
  DEF_x__h2810 = DEF_a__h2795 & DEF_b__h2796;
  DEF_x__h2594 = DEF_a__h2579 & DEF_b__h2580;
  DEF_x__h1693 = DEF_a__h1678 & DEF_b__h1679;
  DEF_x__h1909 = DEF_a__h1894 & DEF_b__h1895;
  DEF_y__h1692 = DEF_b__h1679 & DEF_c__h1790;
  DEF_y__h1694 = DEF_a__h1678 & DEF_c__h1790;
  DEF_x__h1691 = DEF_x__h1693 | DEF_y__h1694;
  DEF_c__h2006 = DEF_x__h1691 | DEF_y__h1692;
  DEF_y__h1910 = DEF_a__h1894 & DEF_c__h2006;
  DEF_x__h1907 = DEF_x__h1909 | DEF_y__h1910;
  DEF_y__h1908 = DEF_b__h1895 & DEF_c__h2006;
  DEF_c__h2221 = DEF_x__h1907 | DEF_y__h1908;
  DEF_y__h2124 = DEF_b__h2111 & DEF_c__h2221;
  DEF_x__h2125 = DEF_a__h2110 & DEF_b__h2111;
  DEF_y__h2126 = DEF_a__h2110 & DEF_c__h2221;
  DEF_x__h2123 = DEF_x__h2125 | DEF_y__h2126;
  DEF_c0__h1143 = DEF_x__h2123 | DEF_y__h2124;
  DEF_y__h2339 = DEF_b__h2326 & DEF_c0__h1143;
  DEF_y__h2341 = DEF_a__h2325 & DEF_c0__h1143;
  DEF_x__h2338 = DEF_x__h2340 | DEF_y__h2341;
  DEF_c__h2691 = DEF_x__h2338 | DEF_y__h2339;
  DEF_y__h2593 = DEF_b__h2580 & DEF_c__h2691;
  DEF_y__h2595 = DEF_a__h2579 & DEF_c__h2691;
  DEF_x__h2592 = DEF_x__h2594 | DEF_y__h2595;
  DEF_c__h2907 = DEF_x__h2592 | DEF_y__h2593;
  DEF_y__h2809 = DEF_b__h2796 & DEF_c__h2907;
  DEF_y__h2811 = DEF_a__h2795 & DEF_c__h2907;
  DEF_x__h2808 = DEF_x__h2810 | DEF_y__h2811;
  DEF_c__h3122 = DEF_x__h2808 | DEF_y__h2809;
  DEF_y__h3025 = DEF_b__h3012 & DEF_c__h3122;
  DEF_y__h3027 = DEF_a__h3011 & DEF_c__h3122;
  DEF_x__h3024 = DEF_x__h3026 | DEF_y__h3027;
  DEF_x__h3376 = DEF_x__h945 + 1u;
  DEF_high__h1138 = (tUInt8)31u & ((((((DEF_x__h3024 | DEF_y__h3025) << 4u) | ((DEF_x__h3133 ^ DEF_c__h3122) << 3u)) | ((DEF_x__h2918 ^ DEF_c__h2907) << 2u)) | ((DEF_x__h2702 ^ DEF_c__h2691) << 1u)) | (DEF_x__h2487 ^ DEF_c0__h1143));
  DEF_v__h1133 = 511u & (((((((tUInt32)(DEF_high__h1138)) << 4u) | (((tUInt32)(DEF_x__h2232 ^ DEF_c__h2221)) << 3u)) | (((tUInt32)(DEF_x__h2017 ^ DEF_c__h2006)) << 2u)) | (((tUInt32)(DEF_x__h1801 ^ DEF_c__h1790)) << 1u)) | (tUInt32)(DEF_a__h1422 ^ DEF_b__h1423));
  DEF_NOT_cycle_5_EQ_0_6_1_AND_NOT_cycle_5_EQ_128_7__ETC___d100 = !DEF_cycle_5_EQ_0___d16 && (!DEF_cycle_5_EQ_128___d17 && !(DEF_v__h1133 == DEF_realAns__h3247));
  if (DEF_cycle_5_EQ_0___d16)
    INST_randomVal1_initialized.METH_write((tUInt8)1u);
  if (DEF_cycle_5_EQ_0___d16)
    INST_randomVal2_initialized.METH_write((tUInt8)1u);
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    if (DEF_cycle_5_EQ_128___d17)
      dollar_display(sim_hdl, this, "s", &__str_literal_1);
    if (DEF_cycle_5_EQ_128___d17)
      dollar_finish(sim_hdl, "32", 1u);
    if (DEF_NOT_cycle_5_EQ_0_6_1_AND_NOT_cycle_5_EQ_128_7__ETC___d100)
      dollar_display(sim_hdl,
		     this,
		     "s,8,8,9,9",
		     &__str_literal_2,
		     DEF_v__h389,
		     DEF_v__h764,
		     DEF_v__h1133,
		     DEF_realAns__h3247);
    if (DEF_NOT_cycle_5_EQ_0_6_1_AND_NOT_cycle_5_EQ_128_7__ETC___d100)
      dollar_finish(sim_hdl, "32", 1u);
  }
  INST_cycle.METH_write(DEF_x__h3376);
}


/* Methods */


/* Reset routines */

void MOD_mkTbRCA::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_randomVal2_initialized.reset_RST(ARG_rst_in);
  INST_randomVal1_initialized.reset_RST(ARG_rst_in);
  INST_cycle.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkTbRCA::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkTbRCA::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_cycle.dump_state(indent + 2u);
  INST_randomVal1_ignore.dump_state(indent + 2u);
  INST_randomVal1_initialized.dump_state(indent + 2u);
  INST_randomVal1_zaz.dump_state(indent + 2u);
  INST_randomVal2_ignore.dump_state(indent + 2u);
  INST_randomVal2_initialized.dump_state(indent + 2u);
  INST_randomVal2_zaz.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkTbRCA::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 17u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "cycle_5_EQ_0___d16", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "cycle_5_EQ_128___d17", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h315", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h389", 8u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h691", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h764", 8u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h945", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x_wget__h250", 8u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x_wget__h634", 8u);
  num = INST_cycle.dump_VCD_defs(num);
  num = INST_randomVal1_ignore.dump_VCD_defs(num);
  num = INST_randomVal1_initialized.dump_VCD_defs(num);
  num = INST_randomVal1_zaz.dump_VCD_defs(num);
  num = INST_randomVal2_ignore.dump_VCD_defs(num);
  num = INST_randomVal2_initialized.dump_VCD_defs(num);
  num = INST_randomVal2_zaz.dump_VCD_defs(num);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkTbRCA::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTbRCA &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
}

void MOD_mkTbRCA::vcd_defs(tVCDDumpType dt, MOD_mkTbRCA &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 8u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_cycle_5_EQ_0___d16) != DEF_cycle_5_EQ_0___d16)
      {
	vcd_write_val(sim_hdl, num, DEF_cycle_5_EQ_0___d16, 1u);
	backing.DEF_cycle_5_EQ_0___d16 = DEF_cycle_5_EQ_0___d16;
      }
      ++num;
      if ((backing.DEF_cycle_5_EQ_128___d17) != DEF_cycle_5_EQ_128___d17)
      {
	vcd_write_val(sim_hdl, num, DEF_cycle_5_EQ_128___d17, 1u);
	backing.DEF_cycle_5_EQ_128___d17 = DEF_cycle_5_EQ_128___d17;
      }
      ++num;
      if ((backing.DEF_v__h315) != DEF_v__h315)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h315, 32u);
	backing.DEF_v__h315 = DEF_v__h315;
      }
      ++num;
      if ((backing.DEF_v__h389) != DEF_v__h389)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h389, 8u);
	backing.DEF_v__h389 = DEF_v__h389;
      }
      ++num;
      if ((backing.DEF_v__h691) != DEF_v__h691)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h691, 32u);
	backing.DEF_v__h691 = DEF_v__h691;
      }
      ++num;
      if ((backing.DEF_v__h764) != DEF_v__h764)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h764, 8u);
	backing.DEF_v__h764 = DEF_v__h764;
      }
      ++num;
      if ((backing.DEF_x__h945) != DEF_x__h945)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h945, 32u);
	backing.DEF_x__h945 = DEF_x__h945;
      }
      ++num;
      if ((backing.DEF_x_wget__h250) != DEF_x_wget__h250)
      {
	vcd_write_val(sim_hdl, num, DEF_x_wget__h250, 8u);
	backing.DEF_x_wget__h250 = DEF_x_wget__h250;
      }
      ++num;
      if ((backing.DEF_x_wget__h634) != DEF_x_wget__h634)
      {
	vcd_write_val(sim_hdl, num, DEF_x_wget__h634, 8u);
	backing.DEF_x_wget__h634 = DEF_x_wget__h634;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_cycle_5_EQ_0___d16, 1u);
      backing.DEF_cycle_5_EQ_0___d16 = DEF_cycle_5_EQ_0___d16;
      vcd_write_val(sim_hdl, num++, DEF_cycle_5_EQ_128___d17, 1u);
      backing.DEF_cycle_5_EQ_128___d17 = DEF_cycle_5_EQ_128___d17;
      vcd_write_val(sim_hdl, num++, DEF_v__h315, 32u);
      backing.DEF_v__h315 = DEF_v__h315;
      vcd_write_val(sim_hdl, num++, DEF_v__h389, 8u);
      backing.DEF_v__h389 = DEF_v__h389;
      vcd_write_val(sim_hdl, num++, DEF_v__h691, 32u);
      backing.DEF_v__h691 = DEF_v__h691;
      vcd_write_val(sim_hdl, num++, DEF_v__h764, 8u);
      backing.DEF_v__h764 = DEF_v__h764;
      vcd_write_val(sim_hdl, num++, DEF_x__h945, 32u);
      backing.DEF_x__h945 = DEF_x__h945;
      vcd_write_val(sim_hdl, num++, DEF_x_wget__h250, 8u);
      backing.DEF_x_wget__h250 = DEF_x_wget__h250;
      vcd_write_val(sim_hdl, num++, DEF_x_wget__h634, 8u);
      backing.DEF_x_wget__h634 = DEF_x_wget__h634;
    }
}

void MOD_mkTbRCA::vcd_prims(tVCDDumpType dt, MOD_mkTbRCA &backing)
{
  INST_cycle.dump_VCD(dt, backing.INST_cycle);
  INST_randomVal1_ignore.dump_VCD(dt, backing.INST_randomVal1_ignore);
  INST_randomVal1_initialized.dump_VCD(dt, backing.INST_randomVal1_initialized);
  INST_randomVal1_zaz.dump_VCD(dt, backing.INST_randomVal1_zaz);
  INST_randomVal2_ignore.dump_VCD(dt, backing.INST_randomVal2_ignore);
  INST_randomVal2_initialized.dump_VCD(dt, backing.INST_randomVal2_initialized);
  INST_randomVal2_zaz.dump_VCD(dt, backing.INST_randomVal2_zaz);
}
