/*
 * Generated by Bluespec Compiler, version 2023.01 (build 52adafa5)
 * 
 * On Wed Sep  6 08:43:37 UTC 2023
 * 
 */
#include "bluesim_primitives.h"
#include "mkTbCSA.h"
#include "imported_BDPI_functions.h"


/* String declarations */
static std::string const __str_literal_2("FAILED %d + %d gave %d instead of %d", 36u);
static std::string const __str_literal_1("PASSED", 6u);


/* Constructor */
MOD_mkTbCSA::MOD_mkTbCSA(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_cycle(simHdl, "cycle", this, 32u, 0u, (tUInt8)0u),
    INST_randomVal1_ignore(simHdl, "randomVal1_ignore", this, 8u, (tUInt8)0u),
    INST_randomVal1_initialized(simHdl, "randomVal1_initialized", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_randomVal1_zaz(simHdl, "randomVal1_zaz", this, 8u, (tUInt8)0u),
    INST_randomVal2_ignore(simHdl, "randomVal2_ignore", this, 8u, (tUInt8)0u),
    INST_randomVal2_initialized(simHdl, "randomVal2_initialized", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_randomVal2_zaz(simHdl, "randomVal2_zaz", this, 8u, (tUInt8)0u),
    PORT_RST_N((tUInt8)1u),
    DEF_v__h691(2863311530u),
    DEF_v__h315(2863311530u)
{
  symbol_count = 13u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkTbCSA::init_symbols_0()
{
  init_symbol(&symbols[0u], "cycle", SYM_MODULE, &INST_cycle);
  init_symbol(&symbols[1u], "RL_randomVal1_every", SYM_RULE);
  init_symbol(&symbols[2u], "RL_randomVal1_every_1", SYM_RULE);
  init_symbol(&symbols[3u], "RL_randomVal2_every", SYM_RULE);
  init_symbol(&symbols[4u], "RL_randomVal2_every_1", SYM_RULE);
  init_symbol(&symbols[5u], "RL_test", SYM_RULE);
  init_symbol(&symbols[6u], "randomVal1_ignore", SYM_MODULE, &INST_randomVal1_ignore);
  init_symbol(&symbols[7u], "randomVal1_initialized", SYM_MODULE, &INST_randomVal1_initialized);
  init_symbol(&symbols[8u], "randomVal1_zaz", SYM_MODULE, &INST_randomVal1_zaz);
  init_symbol(&symbols[9u], "randomVal2_ignore", SYM_MODULE, &INST_randomVal2_ignore);
  init_symbol(&symbols[10u], "randomVal2_initialized", SYM_MODULE, &INST_randomVal2_initialized);
  init_symbol(&symbols[11u], "randomVal2_zaz", SYM_MODULE, &INST_randomVal2_zaz);
  init_symbol(&symbols[12u], "x__h945", SYM_DEF, &DEF_x__h945, 32u);
}


/* Rule actions */

void MOD_mkTbCSA::RL_randomVal1_every()
{
  tUInt8 DEF_new_value__h357;
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h315 = rand32();
  DEF_new_value__h357 = (tUInt8)((tUInt8)255u & DEF_v__h315);
  INST_randomVal1_zaz.METH_wset(DEF_new_value__h357);
}

void MOD_mkTbCSA::RL_randomVal1_every_1()
{
  DEF_x_wget__h250 = INST_randomVal1_zaz.METH_wget();
  DEF_v__h389 = INST_randomVal1_zaz.METH_whas() ? DEF_x_wget__h250 : (tUInt8)0u;
  INST_randomVal1_ignore.METH_wset(DEF_v__h389);
}

void MOD_mkTbCSA::RL_randomVal2_every()
{
  tUInt8 DEF_new_value__h733;
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h691 = rand32();
  DEF_new_value__h733 = (tUInt8)((tUInt8)255u & DEF_v__h691);
  INST_randomVal2_zaz.METH_wset(DEF_new_value__h733);
}

void MOD_mkTbCSA::RL_randomVal2_every_1()
{
  DEF_x_wget__h634 = INST_randomVal2_zaz.METH_wget();
  DEF_v__h764 = INST_randomVal2_zaz.METH_whas() ? DEF_x_wget__h634 : (tUInt8)0u;
  INST_randomVal2_ignore.METH_wset(DEF_v__h764);
}

void MOD_mkTbCSA::RL_test()
{
  tUInt32 DEF_x__h4409;
  tUInt8 DEF_y__h3843;
  tUInt8 DEF_y__h2814;
  tUInt8 DEF_x__h2813;
  tUInt8 DEF_y__h1998;
  tUInt8 DEF_y__h1782;
  tUInt8 DEF_y__h3627;
  tUInt8 DEF_y__h2598;
  tUInt8 DEF_x__h2597;
  tUInt8 DEF_x__h2340;
  tUInt8 DEF_y__h2596;
  tUInt8 DEF_x__h2595;
  tUInt8 DEF_y__h1568;
  tUInt8 DEF_x__h1567;
  tUInt8 DEF_y__h2812;
  tUInt8 DEF_x__h2811;
  tUInt8 DEF_y__h1784;
  tUInt8 DEF_x__h1783;
  tUInt8 DEF_x__h1781;
  tUInt8 DEF_y__h3028;
  tUInt8 DEF_y__h2000;
  tUInt8 DEF_x__h1999;
  tUInt8 DEF_x__h1997;
  tUInt8 DEF_y__h3625;
  tUInt8 DEF_x__h3624;
  tUInt8 DEF_y__h3841;
  tUInt8 DEF_x__h3840;
  tUInt8 DEF_y__h4057;
  tUInt8 DEF_y__h1566;
  tUInt8 DEF_x__h1565;
  tUInt8 DEF_y__h4059;
  tUInt8 DEF_x__h4056;
  tUInt8 DEF_y__h3030;
  tUInt8 DEF_x__h3029;
  tUInt8 DEF_x__h3027;
  tUInt8 DEF_c__h2910;
  tUInt8 DEF_c__h3939;
  tUInt8 DEF_x__h2921;
  tUInt8 DEF_c__h3723;
  tUInt8 DEF_c__h2584;
  tUInt8 DEF_x__h2705;
  tUInt8 DEF_c__h3125;
  tUInt8 DEF_c__h4154;
  tUInt8 DEF_x__h3136;
  tUInt8 DEF_c__h2095;
  tUInt8 DEF_x__h2106;
  tUInt8 DEF_c__h1880;
  tUInt8 DEF_x__h1891;
  tUInt8 DEF_c__h1664;
  tUInt8 DEF_x__h1675;
  tUInt8 DEF_IF_randomVal1_zaz_whas_THEN_randomVal1_zaz_wge_ETC___d79;
  tUInt8 DEF_NOT_cycle_5_EQ_0_6_1_AND_NOT_cycle_5_EQ_128_7__ETC___d116;
  tUInt32 DEF_realAns__h4280;
  tUInt32 DEF_v__h1133;
  tUInt8 DEF_b__h1297;
  tUInt8 DEF_b__h1553;
  tUInt8 DEF_b__h1769;
  tUInt8 DEF_b__h1985;
  tUInt8 DEF_b__h2328;
  tUInt8 DEF_b__h2583;
  tUInt8 DEF_b__h2799;
  tUInt8 DEF_b__h3015;
  tUInt8 DEF_a__h1296;
  tUInt8 DEF_a__h1552;
  tUInt8 DEF_a__h1768;
  tUInt8 DEF_a__h1984;
  tUInt8 DEF_a__h2327;
  tUInt8 DEF_a__h2582;
  tUInt8 DEF_a__h2798;
  tUInt8 DEF_a__h3014;
  DEF_x__h945 = INST_cycle.METH_read();
  DEF_x_wget__h634 = INST_randomVal2_zaz.METH_wget();
  DEF_x_wget__h250 = INST_randomVal1_zaz.METH_wget();
  DEF_v__h389 = INST_randomVal1_zaz.METH_whas() ? DEF_x_wget__h250 : (tUInt8)0u;
  DEF_a__h3014 = (tUInt8)(DEF_v__h389 >> 7u);
  DEF_a__h2798 = (tUInt8)((tUInt8)1u & (DEF_v__h389 >> 6u));
  DEF_a__h2582 = (tUInt8)((tUInt8)1u & (DEF_v__h389 >> 5u));
  DEF_a__h2327 = (tUInt8)((tUInt8)1u & (DEF_v__h389 >> 4u));
  DEF_a__h1984 = (tUInt8)((tUInt8)1u & (DEF_v__h389 >> 3u));
  DEF_a__h1768 = (tUInt8)((tUInt8)1u & (DEF_v__h389 >> 2u));
  DEF_a__h1552 = (tUInt8)((tUInt8)1u & (DEF_v__h389 >> 1u));
  DEF_a__h1296 = (tUInt8)((tUInt8)1u & DEF_v__h389);
  DEF_v__h764 = INST_randomVal2_zaz.METH_whas() ? DEF_x_wget__h634 : (tUInt8)0u;
  DEF_b__h3015 = (tUInt8)(DEF_v__h764 >> 7u);
  DEF_b__h2799 = (tUInt8)((tUInt8)1u & (DEF_v__h764 >> 6u));
  DEF_b__h2583 = (tUInt8)((tUInt8)1u & (DEF_v__h764 >> 5u));
  DEF_b__h2328 = (tUInt8)((tUInt8)1u & (DEF_v__h764 >> 4u));
  DEF_b__h1985 = (tUInt8)((tUInt8)1u & (DEF_v__h764 >> 3u));
  DEF_b__h1769 = (tUInt8)((tUInt8)1u & (DEF_v__h764 >> 2u));
  DEF_b__h1553 = (tUInt8)((tUInt8)1u & (DEF_v__h764 >> 1u));
  DEF_b__h1297 = (tUInt8)((tUInt8)1u & DEF_v__h764);
  DEF_cycle_5_EQ_128___d17 = DEF_x__h945 == 128u;
  DEF_cycle_5_EQ_0___d16 = DEF_x__h945 == 0u;
  DEF_realAns__h4280 = 511u & ((511u & ((((tUInt32)((tUInt8)0u)) << 8u) | (tUInt32)(DEF_v__h389))) + (511u & ((((tUInt32)((tUInt8)0u)) << 8u) | (tUInt32)(DEF_v__h764))));
  DEF_IF_randomVal1_zaz_whas_THEN_randomVal1_zaz_wge_ETC___d79 = DEF_a__h2327 ^ DEF_b__h2328;
  DEF_x__h1675 = DEF_a__h1552 ^ DEF_b__h1553;
  DEF_c__h1664 = DEF_a__h1296 & DEF_b__h1297;
  DEF_x__h2106 = DEF_a__h1984 ^ DEF_b__h1985;
  DEF_x__h1891 = DEF_a__h1768 ^ DEF_b__h1769;
  DEF_x__h3136 = DEF_a__h3014 ^ DEF_b__h3015;
  DEF_x__h2705 = DEF_a__h2582 ^ DEF_b__h2583;
  DEF_c__h3723 = DEF_a__h2327 & DEF_b__h2328;
  DEF_x__h2921 = DEF_a__h2798 ^ DEF_b__h2799;
  DEF_x__h3029 = DEF_a__h3014 & DEF_b__h3015;
  DEF_y__h1566 = DEF_b__h1553 & DEF_c__h1664;
  DEF_y__h3625 = DEF_b__h2583 & DEF_c__h3723;
  DEF_x__h1999 = DEF_a__h1984 & DEF_b__h1985;
  DEF_x__h1783 = DEF_a__h1768 & DEF_b__h1769;
  DEF_x__h1567 = DEF_a__h1552 & DEF_b__h1553;
  DEF_y__h1568 = DEF_a__h1552 & DEF_c__h1664;
  DEF_x__h1565 = DEF_x__h1567 | DEF_y__h1568;
  DEF_c__h1880 = DEF_x__h1565 | DEF_y__h1566;
  DEF_y__h1784 = DEF_a__h1768 & DEF_c__h1880;
  DEF_x__h1781 = DEF_x__h1783 | DEF_y__h1784;
  DEF_x__h2340 = DEF_c__h3723 | DEF_a__h2327;
  DEF_c__h2584 = DEF_x__h2340 | DEF_b__h2328;
  DEF_y__h2596 = DEF_b__h2583 & DEF_c__h2584;
  DEF_x__h2597 = DEF_a__h2582 & DEF_b__h2583;
  DEF_y__h2598 = DEF_a__h2582 & DEF_c__h2584;
  DEF_x__h2595 = DEF_x__h2597 | DEF_y__h2598;
  DEF_c__h2910 = DEF_x__h2595 | DEF_y__h2596;
  DEF_y__h2812 = DEF_b__h2799 & DEF_c__h2910;
  DEF_y__h3627 = DEF_a__h2582 & DEF_c__h3723;
  DEF_x__h3624 = DEF_x__h2597 | DEF_y__h3627;
  DEF_c__h3939 = DEF_x__h3624 | DEF_y__h3625;
  DEF_y__h3841 = DEF_b__h2799 & DEF_c__h3939;
  DEF_y__h1782 = DEF_b__h1769 & DEF_c__h1880;
  DEF_c__h2095 = DEF_x__h1781 | DEF_y__h1782;
  DEF_y__h2000 = DEF_a__h1984 & DEF_c__h2095;
  DEF_x__h1997 = DEF_x__h1999 | DEF_y__h2000;
  DEF_y__h1998 = DEF_b__h1985 & DEF_c__h2095;
  DEF_x__h2813 = DEF_a__h2798 & DEF_b__h2799;
  DEF_y__h2814 = DEF_a__h2798 & DEF_c__h2910;
  DEF_x__h2811 = DEF_x__h2813 | DEF_y__h2814;
  DEF_c__h3125 = DEF_x__h2811 | DEF_y__h2812;
  DEF_y__h3030 = DEF_a__h3014 & DEF_c__h3125;
  DEF_x__h3027 = DEF_x__h3029 | DEF_y__h3030;
  DEF_y__h3028 = DEF_b__h3015 & DEF_c__h3125;
  DEF_y__h3843 = DEF_a__h2798 & DEF_c__h3939;
  DEF_x__h3840 = DEF_x__h2813 | DEF_y__h3843;
  DEF_c__h4154 = DEF_x__h3840 | DEF_y__h3841;
  DEF_y__h4059 = DEF_a__h3014 & DEF_c__h4154;
  DEF_x__h4056 = DEF_x__h3029 | DEF_y__h4059;
  DEF_y__h4057 = DEF_b__h3015 & DEF_c__h4154;
  DEF_v__h1133 = 511u & (((((((tUInt32)(DEF_x__h1997 | DEF_y__h1998 ? (tUInt8)31u & ((((((DEF_x__h3027 | DEF_y__h3028) << 4u) | ((DEF_x__h3136 ^ DEF_c__h3125) << 3u)) | ((DEF_x__h2921 ^ DEF_c__h2910) << 2u)) | ((DEF_x__h2705 ^ DEF_c__h2584) << 1u)) | ((tUInt8)1u & ~DEF_IF_randomVal1_zaz_whas_THEN_randomVal1_zaz_wge_ETC___d79)) : (tUInt8)31u & ((((((DEF_x__h4056 | DEF_y__h4057) << 4u) | ((DEF_x__h3136 ^ DEF_c__h4154) << 3u)) | ((DEF_x__h2921 ^ DEF_c__h3939) << 2u)) | ((DEF_x__h2705 ^ DEF_c__h3723) << 1u)) | DEF_IF_randomVal1_zaz_whas_THEN_randomVal1_zaz_wge_ETC___d79))) << 4u) | (((tUInt32)(DEF_x__h2106 ^ DEF_c__h2095)) << 3u)) | (((tUInt32)(DEF_x__h1891 ^ DEF_c__h1880)) << 2u)) | (((tUInt32)(DEF_x__h1675 ^ DEF_c__h1664)) << 1u)) | (tUInt32)(DEF_a__h1296 ^ DEF_b__h1297));
  DEF_NOT_cycle_5_EQ_0_6_1_AND_NOT_cycle_5_EQ_128_7__ETC___d116 = !DEF_cycle_5_EQ_0___d16 && (!DEF_cycle_5_EQ_128___d17 && !(DEF_v__h1133 == DEF_realAns__h4280));
  DEF_x__h4409 = DEF_x__h945 + 1u;
  if (DEF_cycle_5_EQ_0___d16)
    INST_randomVal1_initialized.METH_write((tUInt8)1u);
  if (DEF_cycle_5_EQ_0___d16)
    INST_randomVal2_initialized.METH_write((tUInt8)1u);
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    if (DEF_cycle_5_EQ_128___d17)
      dollar_display(sim_hdl, this, "s", &__str_literal_1);
    if (DEF_cycle_5_EQ_128___d17)
      dollar_finish(sim_hdl, "32", 1u);
    if (DEF_NOT_cycle_5_EQ_0_6_1_AND_NOT_cycle_5_EQ_128_7__ETC___d116)
      dollar_display(sim_hdl,
		     this,
		     "s,8,8,9,9",
		     &__str_literal_2,
		     DEF_v__h389,
		     DEF_v__h764,
		     DEF_v__h1133,
		     DEF_realAns__h4280);
    if (DEF_NOT_cycle_5_EQ_0_6_1_AND_NOT_cycle_5_EQ_128_7__ETC___d116)
      dollar_finish(sim_hdl, "32", 1u);
  }
  INST_cycle.METH_write(DEF_x__h4409);
}


/* Methods */


/* Reset routines */

void MOD_mkTbCSA::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_randomVal2_initialized.reset_RST(ARG_rst_in);
  INST_randomVal1_initialized.reset_RST(ARG_rst_in);
  INST_cycle.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkTbCSA::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkTbCSA::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_cycle.dump_state(indent + 2u);
  INST_randomVal1_ignore.dump_state(indent + 2u);
  INST_randomVal1_initialized.dump_state(indent + 2u);
  INST_randomVal1_zaz.dump_state(indent + 2u);
  INST_randomVal2_ignore.dump_state(indent + 2u);
  INST_randomVal2_initialized.dump_state(indent + 2u);
  INST_randomVal2_zaz.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkTbCSA::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 17u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "cycle_5_EQ_0___d16", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "cycle_5_EQ_128___d17", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h315", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h389", 8u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h691", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h764", 8u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h945", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x_wget__h250", 8u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x_wget__h634", 8u);
  num = INST_cycle.dump_VCD_defs(num);
  num = INST_randomVal1_ignore.dump_VCD_defs(num);
  num = INST_randomVal1_initialized.dump_VCD_defs(num);
  num = INST_randomVal1_zaz.dump_VCD_defs(num);
  num = INST_randomVal2_ignore.dump_VCD_defs(num);
  num = INST_randomVal2_initialized.dump_VCD_defs(num);
  num = INST_randomVal2_zaz.dump_VCD_defs(num);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkTbCSA::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTbCSA &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
}

void MOD_mkTbCSA::vcd_defs(tVCDDumpType dt, MOD_mkTbCSA &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 8u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_cycle_5_EQ_0___d16) != DEF_cycle_5_EQ_0___d16)
      {
	vcd_write_val(sim_hdl, num, DEF_cycle_5_EQ_0___d16, 1u);
	backing.DEF_cycle_5_EQ_0___d16 = DEF_cycle_5_EQ_0___d16;
      }
      ++num;
      if ((backing.DEF_cycle_5_EQ_128___d17) != DEF_cycle_5_EQ_128___d17)
      {
	vcd_write_val(sim_hdl, num, DEF_cycle_5_EQ_128___d17, 1u);
	backing.DEF_cycle_5_EQ_128___d17 = DEF_cycle_5_EQ_128___d17;
      }
      ++num;
      if ((backing.DEF_v__h315) != DEF_v__h315)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h315, 32u);
	backing.DEF_v__h315 = DEF_v__h315;
      }
      ++num;
      if ((backing.DEF_v__h389) != DEF_v__h389)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h389, 8u);
	backing.DEF_v__h389 = DEF_v__h389;
      }
      ++num;
      if ((backing.DEF_v__h691) != DEF_v__h691)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h691, 32u);
	backing.DEF_v__h691 = DEF_v__h691;
      }
      ++num;
      if ((backing.DEF_v__h764) != DEF_v__h764)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h764, 8u);
	backing.DEF_v__h764 = DEF_v__h764;
      }
      ++num;
      if ((backing.DEF_x__h945) != DEF_x__h945)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h945, 32u);
	backing.DEF_x__h945 = DEF_x__h945;
      }
      ++num;
      if ((backing.DEF_x_wget__h250) != DEF_x_wget__h250)
      {
	vcd_write_val(sim_hdl, num, DEF_x_wget__h250, 8u);
	backing.DEF_x_wget__h250 = DEF_x_wget__h250;
      }
      ++num;
      if ((backing.DEF_x_wget__h634) != DEF_x_wget__h634)
      {
	vcd_write_val(sim_hdl, num, DEF_x_wget__h634, 8u);
	backing.DEF_x_wget__h634 = DEF_x_wget__h634;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_cycle_5_EQ_0___d16, 1u);
      backing.DEF_cycle_5_EQ_0___d16 = DEF_cycle_5_EQ_0___d16;
      vcd_write_val(sim_hdl, num++, DEF_cycle_5_EQ_128___d17, 1u);
      backing.DEF_cycle_5_EQ_128___d17 = DEF_cycle_5_EQ_128___d17;
      vcd_write_val(sim_hdl, num++, DEF_v__h315, 32u);
      backing.DEF_v__h315 = DEF_v__h315;
      vcd_write_val(sim_hdl, num++, DEF_v__h389, 8u);
      backing.DEF_v__h389 = DEF_v__h389;
      vcd_write_val(sim_hdl, num++, DEF_v__h691, 32u);
      backing.DEF_v__h691 = DEF_v__h691;
      vcd_write_val(sim_hdl, num++, DEF_v__h764, 8u);
      backing.DEF_v__h764 = DEF_v__h764;
      vcd_write_val(sim_hdl, num++, DEF_x__h945, 32u);
      backing.DEF_x__h945 = DEF_x__h945;
      vcd_write_val(sim_hdl, num++, DEF_x_wget__h250, 8u);
      backing.DEF_x_wget__h250 = DEF_x_wget__h250;
      vcd_write_val(sim_hdl, num++, DEF_x_wget__h634, 8u);
      backing.DEF_x_wget__h634 = DEF_x_wget__h634;
    }
}

void MOD_mkTbCSA::vcd_prims(tVCDDumpType dt, MOD_mkTbCSA &backing)
{
  INST_cycle.dump_VCD(dt, backing.INST_cycle);
  INST_randomVal1_ignore.dump_VCD(dt, backing.INST_randomVal1_ignore);
  INST_randomVal1_initialized.dump_VCD(dt, backing.INST_randomVal1_initialized);
  INST_randomVal1_zaz.dump_VCD(dt, backing.INST_randomVal1_zaz);
  INST_randomVal2_ignore.dump_VCD(dt, backing.INST_randomVal2_ignore);
  INST_randomVal2_initialized.dump_VCD(dt, backing.INST_randomVal2_initialized);
  INST_randomVal2_zaz.dump_VCD(dt, backing.INST_randomVal2_zaz);
}
