/*
 * Generated by Bluespec Compiler, version 2023.01 (build 52adafa5)
 * 
 * On Sun Sep 10 12:45:51 UTC 2023
 * 
 */
#include "bluesim_primitives.h"
#include "mkTbEx7a.h"
#include "imported_BDPI_functions.h"


/* String declarations */
static std::string const __str_literal_2("    if signed: %0d * %0d DUT gave %0d", 37u);
static std::string const __str_literal_5("    if signed: %0d * %0d DUT gave %0d instead of %0d",
					 52u);
static std::string const __str_literal_3("    if unsigned: %0d * %0d DUT gave %0d", 39u);
static std::string const __str_literal_6("    if unsigned: %0d * %0d DUT gave %0d instead of %0d",
					 54u);
static std::string const __str_literal_4("FAILED case %0d", 15u);
static std::string const __str_literal_8("FAILED due to cycle limit", 25u);
static std::string const __str_literal_7("PASSED %0d test cases in %0d cycles", 35u);
static std::string const __str_literal_1("PASSED case %0d", 15u);


/* Constructor */
MOD_mkTbEx7a::MOD_mkTbEx7a(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_mod_i(simHdl, "mod_i", this, 4u, (tUInt8)9u, (tUInt8)0u),
    INST_mod_m_neg(simHdl, "mod_m_neg", this, 17u),
    INST_mod_m_pos(simHdl, "mod_m_pos", this, 17u),
    INST_mod_p(simHdl, "mod_p", this, 17u),
    INST_tb_cycle(simHdl, "tb_cycle", this, 32u, 0u, (tUInt8)0u),
    INST_tb_feed_count(simHdl, "tb_feed_count", this, 32u, 0u, (tUInt8)0u),
    INST_tb_operands_fifo(simHdl, "tb_operands_fifo", this, 16u, 4u, (tUInt8)1u, 0u),
    INST_tb_randomA_ignore(simHdl, "tb_randomA_ignore", this, 8u, (tUInt8)0u),
    INST_tb_randomA_initialized(simHdl, "tb_randomA_initialized", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_tb_randomA_zaz(simHdl, "tb_randomA_zaz", this, 8u, (tUInt8)0u),
    INST_tb_randomB_ignore(simHdl, "tb_randomB_ignore", this, 8u, (tUInt8)0u),
    INST_tb_randomB_initialized(simHdl, "tb_randomB_initialized", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_tb_randomB_zaz(simHdl, "tb_randomB_zaz", this, 8u, (tUInt8)0u),
    INST_tb_read_count(simHdl, "tb_read_count", this, 32u, 0u, (tUInt8)0u),
    PORT_RST_N((tUInt8)1u),
    DEF_v__h1276(2863311530u),
    DEF_v__h899(2863311530u)
{
  symbol_count = 45u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkTbEx7a::init_symbols_0()
{
  init_symbol(&symbols[0u], "_read__h138", SYM_DEF, &DEF__read__h138, 4u);
  init_symbol(&symbols[1u], "CAN_FIRE_RL_mod_mul_step", SYM_DEF, &DEF_CAN_FIRE_RL_mod_mul_step, 1u);
  init_symbol(&symbols[2u], "CAN_FIRE_RL_tb_feed", SYM_DEF, &DEF_CAN_FIRE_RL_tb_feed, 1u);
  init_symbol(&symbols[3u],
	      "CAN_FIRE_RL_tb_monitor_test",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_tb_monitor_test,
	      1u);
  init_symbol(&symbols[4u],
	      "CAN_FIRE_RL_tb_randomA_every",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_tb_randomA_every,
	      1u);
  init_symbol(&symbols[5u],
	      "CAN_FIRE_RL_tb_randomA_every_1",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_tb_randomA_every_1,
	      1u);
  init_symbol(&symbols[6u],
	      "CAN_FIRE_RL_tb_randomB_every",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_tb_randomB_every,
	      1u);
  init_symbol(&symbols[7u],
	      "CAN_FIRE_RL_tb_randomB_every_1",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_tb_randomB_every_1,
	      1u);
  init_symbol(&symbols[8u], "CAN_FIRE_RL_tb_read", SYM_DEF, &DEF_CAN_FIRE_RL_tb_read, 1u);
  init_symbol(&symbols[9u], "mod_i", SYM_MODULE, &INST_mod_i);
  init_symbol(&symbols[10u], "mod_m_neg", SYM_MODULE, &INST_mod_m_neg);
  init_symbol(&symbols[11u], "mod_m_pos", SYM_MODULE, &INST_mod_m_pos);
  init_symbol(&symbols[12u], "mod_p", SYM_MODULE, &INST_mod_p);
  init_symbol(&symbols[13u], "RL_mod_mul_step", SYM_RULE);
  init_symbol(&symbols[14u], "RL_tb_feed", SYM_RULE);
  init_symbol(&symbols[15u], "RL_tb_monitor_test", SYM_RULE);
  init_symbol(&symbols[16u], "RL_tb_randomA_every", SYM_RULE);
  init_symbol(&symbols[17u], "RL_tb_randomA_every_1", SYM_RULE);
  init_symbol(&symbols[18u], "RL_tb_randomB_every", SYM_RULE);
  init_symbol(&symbols[19u], "RL_tb_randomB_every_1", SYM_RULE);
  init_symbol(&symbols[20u], "RL_tb_read", SYM_RULE);
  init_symbol(&symbols[21u], "tb_cycle", SYM_MODULE, &INST_tb_cycle);
  init_symbol(&symbols[22u], "tb_feed_count", SYM_MODULE, &INST_tb_feed_count);
  init_symbol(&symbols[23u], "tb_operands_fifo", SYM_MODULE, &INST_tb_operands_fifo);
  init_symbol(&symbols[24u], "tb_randomA_ignore", SYM_MODULE, &INST_tb_randomA_ignore);
  init_symbol(&symbols[25u], "tb_randomA_initialized", SYM_MODULE, &INST_tb_randomA_initialized);
  init_symbol(&symbols[26u], "tb_randomA_zaz", SYM_MODULE, &INST_tb_randomA_zaz);
  init_symbol(&symbols[27u], "tb_randomB_ignore", SYM_MODULE, &INST_tb_randomB_ignore);
  init_symbol(&symbols[28u], "tb_randomB_initialized", SYM_MODULE, &INST_tb_randomB_initialized);
  init_symbol(&symbols[29u], "tb_randomB_zaz", SYM_MODULE, &INST_tb_randomB_zaz);
  init_symbol(&symbols[30u], "tb_read_count", SYM_MODULE, &INST_tb_read_count);
  init_symbol(&symbols[31u], "v__h1349", SYM_DEF, &DEF_v__h1349, 8u);
  init_symbol(&symbols[32u], "v__h973", SYM_DEF, &DEF_v__h973, 8u);
  init_symbol(&symbols[33u],
	      "WILL_FIRE_RL_mod_mul_step",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_mod_mul_step,
	      1u);
  init_symbol(&symbols[34u], "WILL_FIRE_RL_tb_feed", SYM_DEF, &DEF_WILL_FIRE_RL_tb_feed, 1u);
  init_symbol(&symbols[35u],
	      "WILL_FIRE_RL_tb_monitor_test",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_tb_monitor_test,
	      1u);
  init_symbol(&symbols[36u],
	      "WILL_FIRE_RL_tb_randomA_every",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_tb_randomA_every,
	      1u);
  init_symbol(&symbols[37u],
	      "WILL_FIRE_RL_tb_randomA_every_1",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_tb_randomA_every_1,
	      1u);
  init_symbol(&symbols[38u],
	      "WILL_FIRE_RL_tb_randomB_every",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_tb_randomB_every,
	      1u);
  init_symbol(&symbols[39u],
	      "WILL_FIRE_RL_tb_randomB_every_1",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_tb_randomB_every_1,
	      1u);
  init_symbol(&symbols[40u], "WILL_FIRE_RL_tb_read", SYM_DEF, &DEF_WILL_FIRE_RL_tb_read, 1u);
  init_symbol(&symbols[41u], "x__h1722", SYM_DEF, &DEF_x__h1722, 32u);
  init_symbol(&symbols[42u], "x__h2279", SYM_DEF, &DEF_x__h2279, 32u);
  init_symbol(&symbols[43u], "x_wget__h1219", SYM_DEF, &DEF_x_wget__h1219, 8u);
  init_symbol(&symbols[44u], "x_wget__h842", SYM_DEF, &DEF_x_wget__h842, 8u);
}


/* Rule actions */

void MOD_mkTbEx7a::RL_mod_mul_step()
{
  tUInt32 DEF_a__h345;
  tUInt32 DEF_a__h259;
  tUInt32 DEF_x__h240;
  tUInt32 DEF_IF_mod_p_BITS_1_TO_0_EQ_0b1_THEN_mod_p_PLUS_mo_ETC___d15;
  tUInt32 DEF_x__h376;
  tUInt32 DEF_x__h326;
  tUInt8 DEF_pr__h156;
  tUInt32 DEF_y__h352;
  tUInt32 DEF_y__h281;
  DEF_mod_p__h1825 = INST_mod_p.METH_read();
  DEF_y__h281 = INST_mod_m_pos.METH_read();
  DEF_y__h352 = INST_mod_m_neg.METH_read();
  DEF__read__h138 = INST_mod_i.METH_read();
  DEF_pr__h156 = (tUInt8)((tUInt8)3u & DEF_mod_p__h1825);
  DEF_x__h376 = primShiftRA32(17u, 17u, (tUInt32)(DEF_mod_p__h1825), 32u, 1u);
  DEF_a__h259 = 131071u & (DEF_mod_p__h1825 + DEF_y__h281);
  DEF_x__h240 = primShiftRA32(17u, 17u, (tUInt32)(DEF_a__h259), 32u, 1u);
  DEF_a__h345 = 131071u & (DEF_mod_p__h1825 + DEF_y__h352);
  DEF_x__h326 = primShiftRA32(17u, 17u, (tUInt32)(DEF_a__h345), 32u, 1u);
  switch (DEF_pr__h156) {
  case (tUInt8)1u:
    DEF_IF_mod_p_BITS_1_TO_0_EQ_0b1_THEN_mod_p_PLUS_mo_ETC___d15 = DEF_x__h240;
    break;
  case (tUInt8)2u:
    DEF_IF_mod_p_BITS_1_TO_0_EQ_0b1_THEN_mod_p_PLUS_mo_ETC___d15 = DEF_x__h326;
    break;
  default:
    DEF_IF_mod_p_BITS_1_TO_0_EQ_0b1_THEN_mod_p_PLUS_mo_ETC___d15 = DEF_x__h376;
  }
  DEF_x__h426 = (tUInt8)15u & (DEF__read__h138 + (tUInt8)1u);
  INST_mod_p.METH_write(DEF_IF_mod_p_BITS_1_TO_0_EQ_0b1_THEN_mod_p_PLUS_mo_ETC___d15);
  INST_mod_i.METH_write(DEF_x__h426);
}

void MOD_mkTbEx7a::RL_tb_randomA_every()
{
  tUInt8 DEF_new_value__h941;
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h899 = rand32();
  DEF_new_value__h941 = (tUInt8)((tUInt8)255u & DEF_v__h899);
  INST_tb_randomA_zaz.METH_wset(DEF_new_value__h941);
}

void MOD_mkTbEx7a::RL_tb_randomA_every_1()
{
  DEF_x_wget__h842 = INST_tb_randomA_zaz.METH_wget();
  DEF_tb_randomA_zaz_whas____d21 = INST_tb_randomA_zaz.METH_whas();
  DEF_IF_tb_randomA_zaz_whas__1_THEN_tb_randomA_zaz__ETC___d23 = DEF_x_wget__h842;
  DEF_v__h973 = DEF_tb_randomA_zaz_whas____d21 ? DEF_IF_tb_randomA_zaz_whas__1_THEN_tb_randomA_zaz__ETC___d23 : (tUInt8)0u;
  INST_tb_randomA_ignore.METH_wset(DEF_v__h973);
}

void MOD_mkTbEx7a::RL_tb_randomB_every()
{
  tUInt8 DEF_new_value__h1318;
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h1276 = rand32();
  DEF_new_value__h1318 = (tUInt8)((tUInt8)255u & DEF_v__h1276);
  INST_tb_randomB_zaz.METH_wset(DEF_new_value__h1318);
}

void MOD_mkTbEx7a::RL_tb_randomB_every_1()
{
  DEF_x_wget__h1219 = INST_tb_randomB_zaz.METH_wget();
  DEF_v__h1349 = INST_tb_randomB_zaz.METH_whas() ? DEF_x_wget__h1219 : (tUInt8)0u;
  INST_tb_randomB_ignore.METH_wset(DEF_v__h1349);
}

void MOD_mkTbEx7a::RL_tb_feed()
{
  tUInt32 DEF_IF_tb_randomA_zaz_whas__1_THEN_IF_tb_randomA_z_ETC___d48;
  tUInt32 DEF_x__h1622;
  tUInt32 DEF_x__h1656;
  tUInt32 DEF_x__h1589;
  tUInt32 DEF_x__h1703;
  tUInt8 DEF_NOT_IF_tb_randomA_zaz_whas__1_THEN_IF_tb_rando_ETC___d47;
  DEF_x__h1722 = INST_tb_feed_count.METH_read();
  DEF_x_wget__h1219 = INST_tb_randomB_zaz.METH_wget();
  DEF_x_wget__h842 = INST_tb_randomA_zaz.METH_wget();
  DEF_tb_randomA_zaz_whas____d21 = INST_tb_randomA_zaz.METH_whas();
  DEF_IF_tb_randomA_zaz_whas__1_THEN_tb_randomA_zaz__ETC___d23 = DEF_x_wget__h842;
  DEF_v__h973 = DEF_tb_randomA_zaz_whas____d21 ? DEF_IF_tb_randomA_zaz_whas__1_THEN_tb_randomA_zaz__ETC___d23 : (tUInt8)0u;
  DEF_v__h1349 = INST_tb_randomB_zaz.METH_whas() ? DEF_x_wget__h1219 : (tUInt8)0u;
  DEF_IF_tb_randomB_zaz_whas__9_THEN_tb_randomB_zaz__ETC___d33 = DEF_v__h1349 == (tUInt8)128u;
  DEF_IF_tb_randomA_zaz_whas__1_THEN_IF_tb_randomA_z_ETC___d32 = DEF_v__h973 == (tUInt8)128u;
  DEF_NOT_IF_tb_randomA_zaz_whas__1_THEN_IF_tb_rando_ETC___d47 = !DEF_IF_tb_randomA_zaz_whas__1_THEN_IF_tb_randomA_z_ETC___d32 && !DEF_IF_tb_randomB_zaz_whas__9_THEN_tb_randomB_zaz__ETC___d33;
  DEF_x__h1703 = DEF_x__h1722 + 1u;
  DEF_x__h1589 = 131071u & (((((tUInt32)((tUInt8)0u)) << 9u) | (((tUInt32)(DEF_v__h1349)) << 1u)) | (tUInt32)((tUInt8)0u));
  DEF_x__h1622 = 131071u & (((tUInt32)(DEF_v__h973)) << 9u);
  DEF_x__h1656 = 131071u & (((tUInt32)(DEF_tb_randomA_zaz_whas____d21 ? (tUInt8)255u & -DEF_IF_tb_randomA_zaz_whas__1_THEN_tb_randomA_zaz__ETC___d23 : (tUInt8)0u)) << 9u);
  DEF_IF_tb_randomA_zaz_whas__1_THEN_IF_tb_randomA_z_ETC___d48 = 65535u & ((((tUInt32)(DEF_v__h973)) << 8u) | (tUInt32)(DEF_v__h1349));
  if (DEF_NOT_IF_tb_randomA_zaz_whas__1_THEN_IF_tb_rando_ETC___d47)
    INST_tb_operands_fifo.METH_enq(DEF_IF_tb_randomA_zaz_whas__1_THEN_IF_tb_randomA_z_ETC___d48);
  if (DEF_NOT_IF_tb_randomA_zaz_whas__1_THEN_IF_tb_rando_ETC___d47)
    INST_mod_p.METH_write(DEF_x__h1589);
  if (DEF_NOT_IF_tb_randomA_zaz_whas__1_THEN_IF_tb_rando_ETC___d47)
    INST_mod_m_pos.METH_write(DEF_x__h1622);
  if (DEF_NOT_IF_tb_randomA_zaz_whas__1_THEN_IF_tb_rando_ETC___d47)
    INST_mod_m_neg.METH_write(DEF_x__h1656);
  if (DEF_NOT_IF_tb_randomA_zaz_whas__1_THEN_IF_tb_rando_ETC___d47)
    INST_mod_i.METH_write((tUInt8)0u);
  if (DEF_NOT_IF_tb_randomA_zaz_whas__1_THEN_IF_tb_rando_ETC___d47)
    INST_tb_feed_count.METH_write(DEF_x__h1703);
}

void MOD_mkTbEx7a::RL_tb_read()
{
  tUInt32 DEF_x__h2155;
  tUInt8 DEF_NOT_mod_p_BITS_16_TO_1_2_EQ_SEXT_tb_operands_f_ETC___d74;
  tUInt32 DEF_tb_operands_fifo_first____d63;
  tUInt8 DEF_b__h1743;
  tUInt8 DEF_signed_tb_operands_fifo_first__3_BITS_7_TO_0_6___d72;
  tUInt8 DEF_a__h1742;
  tUInt8 DEF_signed_tb_operands_fifo_first__3_BITS_15_TO_8_4___d71;
  tUInt32 DEF_v__h1767;
  tUInt32 DEF_signed_mod_p_BITS_16_TO_1_2___d73;
  tUInt32 DEF_expected__h1830;
  tUInt32 DEF_signed_SEXT_tb_operands_fifo_first__3_BITS_15_ETC___d75;
  tUInt8 DEF_mod_p_BITS_16_TO_1_2_EQ_SEXT_tb_operands_fifo__ETC___d70;
  DEF_x__h2279 = INST_tb_read_count.METH_read();
  DEF_mod_p__h1825 = INST_mod_p.METH_read();
  DEF_v__h1767 = (tUInt32)(DEF_mod_p__h1825 >> 1u);
  DEF_signed_mod_p_BITS_16_TO_1_2___d73 = DEF_v__h1767;
  DEF_tb_operands_fifo_first____d63 = INST_tb_operands_fifo.METH_first();
  DEF_a__h1742 = (tUInt8)(DEF_tb_operands_fifo_first____d63 >> 8u);
  DEF_signed_tb_operands_fifo_first__3_BITS_15_TO_8_4___d71 = DEF_a__h1742;
  DEF_b__h1743 = (tUInt8)((tUInt8)255u & DEF_tb_operands_fifo_first____d63);
  DEF_expected__h1830 = (tUInt32)(65535u & (primSignExt32(16u,
							  8u,
							  (tUInt8)(DEF_a__h1742)) * primSignExt32(16u,
												  8u,
												  (tUInt8)(DEF_b__h1743))));
  DEF_mod_p_BITS_16_TO_1_2_EQ_SEXT_tb_operands_fifo__ETC___d70 = DEF_v__h1767 == DEF_expected__h1830;
  DEF_signed_SEXT_tb_operands_fifo_first__3_BITS_15_ETC___d75 = DEF_expected__h1830;
  DEF_signed_tb_operands_fifo_first__3_BITS_7_TO_0_6___d72 = DEF_b__h1743;
  DEF__read__h138 = INST_mod_i.METH_read();
  DEF_NOT_mod_p_BITS_16_TO_1_2_EQ_SEXT_tb_operands_f_ETC___d74 = !DEF_mod_p_BITS_16_TO_1_2_EQ_SEXT_tb_operands_fifo__ETC___d70;
  DEF_x__h2155 = DEF_x__h2279 + 1u;
  DEF_x__h426 = (tUInt8)15u & (DEF__read__h138 + (tUInt8)1u);
  INST_tb_operands_fifo.METH_deq();
  INST_mod_i.METH_write(DEF_x__h426);
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    if (DEF_mod_p_BITS_16_TO_1_2_EQ_SEXT_tb_operands_fifo__ETC___d70)
      dollar_display(sim_hdl, this, "s,32", &__str_literal_1, DEF_x__h2279);
    if (DEF_mod_p_BITS_16_TO_1_2_EQ_SEXT_tb_operands_fifo__ETC___d70)
      dollar_display(sim_hdl,
		     this,
		     "s,-8,-8,-16",
		     &__str_literal_2,
		     DEF_signed_tb_operands_fifo_first__3_BITS_15_TO_8_4___d71,
		     DEF_signed_tb_operands_fifo_first__3_BITS_7_TO_0_6___d72,
		     DEF_signed_mod_p_BITS_16_TO_1_2___d73);
    if (DEF_mod_p_BITS_16_TO_1_2_EQ_SEXT_tb_operands_fifo__ETC___d70)
      dollar_display(sim_hdl,
		     this,
		     "s,8,8,16",
		     &__str_literal_3,
		     DEF_a__h1742,
		     DEF_b__h1743,
		     DEF_v__h1767);
    if (DEF_NOT_mod_p_BITS_16_TO_1_2_EQ_SEXT_tb_operands_f_ETC___d74)
      dollar_display(sim_hdl, this, "s,32", &__str_literal_4, DEF_x__h2279);
    if (DEF_NOT_mod_p_BITS_16_TO_1_2_EQ_SEXT_tb_operands_f_ETC___d74)
      dollar_display(sim_hdl,
		     this,
		     "s,-8,-8,-16,-16",
		     &__str_literal_5,
		     DEF_signed_tb_operands_fifo_first__3_BITS_15_TO_8_4___d71,
		     DEF_signed_tb_operands_fifo_first__3_BITS_7_TO_0_6___d72,
		     DEF_signed_mod_p_BITS_16_TO_1_2___d73,
		     DEF_signed_SEXT_tb_operands_fifo_first__3_BITS_15_ETC___d75);
    if (DEF_NOT_mod_p_BITS_16_TO_1_2_EQ_SEXT_tb_operands_f_ETC___d74)
      dollar_display(sim_hdl,
		     this,
		     "s,8,8,16,16",
		     &__str_literal_6,
		     DEF_a__h1742,
		     DEF_b__h1743,
		     DEF_v__h1767,
		     DEF_expected__h1830);
    if (DEF_NOT_mod_p_BITS_16_TO_1_2_EQ_SEXT_tb_operands_f_ETC___d74)
      dollar_finish(sim_hdl, "32", 1u);
  }
  INST_tb_read_count.METH_write(DEF_x__h2155);
}

void MOD_mkTbEx7a::RL_tb_monitor_test()
{
  tUInt32 DEF_x__h2508;
  tUInt8 DEF_tb_cycle_7_EQ_0___d78;
  tUInt8 DEF_tb_cycle_7_EQ_16384___d79;
  tUInt32 DEF_x__h2512;
  DEF_x__h2279 = INST_tb_read_count.METH_read();
  DEF_x__h2512 = INST_tb_cycle.METH_read();
  DEF_tb_cycle_7_EQ_16384___d79 = DEF_x__h2512 == 16384u;
  DEF_tb_cycle_7_EQ_0___d78 = DEF_x__h2512 == 0u;
  DEF_tb_read_count_6_EQ_128___d57 = DEF_x__h2279 == 128u;
  DEF_x__h2508 = DEF_x__h2512 + 1u;
  if (DEF_tb_cycle_7_EQ_0___d78)
    INST_tb_randomA_initialized.METH_write((tUInt8)1u);
  if (DEF_tb_cycle_7_EQ_0___d78)
    INST_tb_randomB_initialized.METH_write((tUInt8)1u);
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    if (DEF_tb_read_count_6_EQ_128___d57)
      dollar_display(sim_hdl, this, "s,32,32", &__str_literal_7, DEF_x__h2279, DEF_x__h2512);
    if (DEF_tb_read_count_6_EQ_128___d57)
      dollar_finish(sim_hdl, "32", 1u);
    if (DEF_tb_cycle_7_EQ_16384___d79)
      dollar_display(sim_hdl, this, "s", &__str_literal_8);
    if (DEF_tb_cycle_7_EQ_16384___d79)
      dollar_finish(sim_hdl, "32", 1u);
  }
  INST_tb_cycle.METH_write(DEF_x__h2508);
}


/* Methods */


/* Reset routines */

void MOD_mkTbEx7a::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_tb_read_count.reset_RST(ARG_rst_in);
  INST_tb_randomB_initialized.reset_RST(ARG_rst_in);
  INST_tb_randomA_initialized.reset_RST(ARG_rst_in);
  INST_tb_operands_fifo.reset_RST(ARG_rst_in);
  INST_tb_feed_count.reset_RST(ARG_rst_in);
  INST_tb_cycle.reset_RST(ARG_rst_in);
  INST_mod_i.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkTbEx7a::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkTbEx7a::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_mod_i.dump_state(indent + 2u);
  INST_mod_m_neg.dump_state(indent + 2u);
  INST_mod_m_pos.dump_state(indent + 2u);
  INST_mod_p.dump_state(indent + 2u);
  INST_tb_cycle.dump_state(indent + 2u);
  INST_tb_feed_count.dump_state(indent + 2u);
  INST_tb_operands_fifo.dump_state(indent + 2u);
  INST_tb_randomA_ignore.dump_state(indent + 2u);
  INST_tb_randomA_initialized.dump_state(indent + 2u);
  INST_tb_randomA_zaz.dump_state(indent + 2u);
  INST_tb_randomB_ignore.dump_state(indent + 2u);
  INST_tb_randomB_initialized.dump_state(indent + 2u);
  INST_tb_randomB_zaz.dump_state(indent + 2u);
  INST_tb_read_count.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkTbEx7a::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 47u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_mod_mul_step", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_tb_feed", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_tb_monitor_test", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_tb_randomA_every", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_tb_randomA_every_1", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_tb_randomB_every", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_tb_randomB_every_1", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_tb_read", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_tb_randomA_zaz_whas__1_THEN_IF_tb_randomA_z_ETC___d32", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_tb_randomA_zaz_whas__1_THEN_tb_randomA_zaz__ETC___d23", 8u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_tb_randomB_zaz_whas__9_THEN_tb_randomB_zaz__ETC___d33", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_mod_mul_step", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_tb_feed", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_tb_monitor_test", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_tb_randomA_every", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_tb_randomA_every_1", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_tb_randomB_every", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_tb_randomB_every_1", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_tb_read", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "_read__h138", 4u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "mod_p__h1825", 17u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "tb_randomA_zaz_whas____d21", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "tb_read_count_6_EQ_128___d57", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h1276", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h1349", 8u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h899", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h973", 8u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h1722", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h2279", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h426", 4u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x_wget__h1219", 8u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x_wget__h842", 8u);
  num = INST_mod_i.dump_VCD_defs(num);
  num = INST_mod_m_neg.dump_VCD_defs(num);
  num = INST_mod_m_pos.dump_VCD_defs(num);
  num = INST_mod_p.dump_VCD_defs(num);
  num = INST_tb_cycle.dump_VCD_defs(num);
  num = INST_tb_feed_count.dump_VCD_defs(num);
  num = INST_tb_operands_fifo.dump_VCD_defs(num);
  num = INST_tb_randomA_ignore.dump_VCD_defs(num);
  num = INST_tb_randomA_initialized.dump_VCD_defs(num);
  num = INST_tb_randomA_zaz.dump_VCD_defs(num);
  num = INST_tb_randomB_ignore.dump_VCD_defs(num);
  num = INST_tb_randomB_initialized.dump_VCD_defs(num);
  num = INST_tb_randomB_zaz.dump_VCD_defs(num);
  num = INST_tb_read_count.dump_VCD_defs(num);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkTbEx7a::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTbEx7a &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
}

void MOD_mkTbEx7a::vcd_defs(tVCDDumpType dt, MOD_mkTbEx7a &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 4u);
    vcd_write_x(sim_hdl, num++, 17u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 4u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 8u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.DEF_CAN_FIRE_RL_mod_mul_step) != DEF_CAN_FIRE_RL_mod_mul_step)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_mod_mul_step, 1u);
	backing.DEF_CAN_FIRE_RL_mod_mul_step = DEF_CAN_FIRE_RL_mod_mul_step;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_tb_feed) != DEF_CAN_FIRE_RL_tb_feed)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_tb_feed, 1u);
	backing.DEF_CAN_FIRE_RL_tb_feed = DEF_CAN_FIRE_RL_tb_feed;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_tb_monitor_test) != DEF_CAN_FIRE_RL_tb_monitor_test)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_tb_monitor_test, 1u);
	backing.DEF_CAN_FIRE_RL_tb_monitor_test = DEF_CAN_FIRE_RL_tb_monitor_test;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_tb_randomA_every) != DEF_CAN_FIRE_RL_tb_randomA_every)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_tb_randomA_every, 1u);
	backing.DEF_CAN_FIRE_RL_tb_randomA_every = DEF_CAN_FIRE_RL_tb_randomA_every;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_tb_randomA_every_1) != DEF_CAN_FIRE_RL_tb_randomA_every_1)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_tb_randomA_every_1, 1u);
	backing.DEF_CAN_FIRE_RL_tb_randomA_every_1 = DEF_CAN_FIRE_RL_tb_randomA_every_1;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_tb_randomB_every) != DEF_CAN_FIRE_RL_tb_randomB_every)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_tb_randomB_every, 1u);
	backing.DEF_CAN_FIRE_RL_tb_randomB_every = DEF_CAN_FIRE_RL_tb_randomB_every;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_tb_randomB_every_1) != DEF_CAN_FIRE_RL_tb_randomB_every_1)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_tb_randomB_every_1, 1u);
	backing.DEF_CAN_FIRE_RL_tb_randomB_every_1 = DEF_CAN_FIRE_RL_tb_randomB_every_1;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_tb_read) != DEF_CAN_FIRE_RL_tb_read)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_tb_read, 1u);
	backing.DEF_CAN_FIRE_RL_tb_read = DEF_CAN_FIRE_RL_tb_read;
      }
      ++num;
      if ((backing.DEF_IF_tb_randomA_zaz_whas__1_THEN_IF_tb_randomA_z_ETC___d32) != DEF_IF_tb_randomA_zaz_whas__1_THEN_IF_tb_randomA_z_ETC___d32)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_tb_randomA_zaz_whas__1_THEN_IF_tb_randomA_z_ETC___d32, 1u);
	backing.DEF_IF_tb_randomA_zaz_whas__1_THEN_IF_tb_randomA_z_ETC___d32 = DEF_IF_tb_randomA_zaz_whas__1_THEN_IF_tb_randomA_z_ETC___d32;
      }
      ++num;
      if ((backing.DEF_IF_tb_randomA_zaz_whas__1_THEN_tb_randomA_zaz__ETC___d23) != DEF_IF_tb_randomA_zaz_whas__1_THEN_tb_randomA_zaz__ETC___d23)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_tb_randomA_zaz_whas__1_THEN_tb_randomA_zaz__ETC___d23, 8u);
	backing.DEF_IF_tb_randomA_zaz_whas__1_THEN_tb_randomA_zaz__ETC___d23 = DEF_IF_tb_randomA_zaz_whas__1_THEN_tb_randomA_zaz__ETC___d23;
      }
      ++num;
      if ((backing.DEF_IF_tb_randomB_zaz_whas__9_THEN_tb_randomB_zaz__ETC___d33) != DEF_IF_tb_randomB_zaz_whas__9_THEN_tb_randomB_zaz__ETC___d33)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_tb_randomB_zaz_whas__9_THEN_tb_randomB_zaz__ETC___d33, 1u);
	backing.DEF_IF_tb_randomB_zaz_whas__9_THEN_tb_randomB_zaz__ETC___d33 = DEF_IF_tb_randomB_zaz_whas__9_THEN_tb_randomB_zaz__ETC___d33;
      }
      ++num;
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_mod_mul_step) != DEF_WILL_FIRE_RL_mod_mul_step)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_mod_mul_step, 1u);
	backing.DEF_WILL_FIRE_RL_mod_mul_step = DEF_WILL_FIRE_RL_mod_mul_step;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_tb_feed) != DEF_WILL_FIRE_RL_tb_feed)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_tb_feed, 1u);
	backing.DEF_WILL_FIRE_RL_tb_feed = DEF_WILL_FIRE_RL_tb_feed;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_tb_monitor_test) != DEF_WILL_FIRE_RL_tb_monitor_test)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_tb_monitor_test, 1u);
	backing.DEF_WILL_FIRE_RL_tb_monitor_test = DEF_WILL_FIRE_RL_tb_monitor_test;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_tb_randomA_every) != DEF_WILL_FIRE_RL_tb_randomA_every)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_tb_randomA_every, 1u);
	backing.DEF_WILL_FIRE_RL_tb_randomA_every = DEF_WILL_FIRE_RL_tb_randomA_every;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_tb_randomA_every_1) != DEF_WILL_FIRE_RL_tb_randomA_every_1)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_tb_randomA_every_1, 1u);
	backing.DEF_WILL_FIRE_RL_tb_randomA_every_1 = DEF_WILL_FIRE_RL_tb_randomA_every_1;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_tb_randomB_every) != DEF_WILL_FIRE_RL_tb_randomB_every)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_tb_randomB_every, 1u);
	backing.DEF_WILL_FIRE_RL_tb_randomB_every = DEF_WILL_FIRE_RL_tb_randomB_every;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_tb_randomB_every_1) != DEF_WILL_FIRE_RL_tb_randomB_every_1)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_tb_randomB_every_1, 1u);
	backing.DEF_WILL_FIRE_RL_tb_randomB_every_1 = DEF_WILL_FIRE_RL_tb_randomB_every_1;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_tb_read) != DEF_WILL_FIRE_RL_tb_read)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_tb_read, 1u);
	backing.DEF_WILL_FIRE_RL_tb_read = DEF_WILL_FIRE_RL_tb_read;
      }
      ++num;
      if ((backing.DEF__read__h138) != DEF__read__h138)
      {
	vcd_write_val(sim_hdl, num, DEF__read__h138, 4u);
	backing.DEF__read__h138 = DEF__read__h138;
      }
      ++num;
      if ((backing.DEF_mod_p__h1825) != DEF_mod_p__h1825)
      {
	vcd_write_val(sim_hdl, num, DEF_mod_p__h1825, 17u);
	backing.DEF_mod_p__h1825 = DEF_mod_p__h1825;
      }
      ++num;
      if ((backing.DEF_tb_randomA_zaz_whas____d21) != DEF_tb_randomA_zaz_whas____d21)
      {
	vcd_write_val(sim_hdl, num, DEF_tb_randomA_zaz_whas____d21, 1u);
	backing.DEF_tb_randomA_zaz_whas____d21 = DEF_tb_randomA_zaz_whas____d21;
      }
      ++num;
      if ((backing.DEF_tb_read_count_6_EQ_128___d57) != DEF_tb_read_count_6_EQ_128___d57)
      {
	vcd_write_val(sim_hdl, num, DEF_tb_read_count_6_EQ_128___d57, 1u);
	backing.DEF_tb_read_count_6_EQ_128___d57 = DEF_tb_read_count_6_EQ_128___d57;
      }
      ++num;
      if ((backing.DEF_v__h1276) != DEF_v__h1276)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h1276, 32u);
	backing.DEF_v__h1276 = DEF_v__h1276;
      }
      ++num;
      if ((backing.DEF_v__h1349) != DEF_v__h1349)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h1349, 8u);
	backing.DEF_v__h1349 = DEF_v__h1349;
      }
      ++num;
      if ((backing.DEF_v__h899) != DEF_v__h899)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h899, 32u);
	backing.DEF_v__h899 = DEF_v__h899;
      }
      ++num;
      if ((backing.DEF_v__h973) != DEF_v__h973)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h973, 8u);
	backing.DEF_v__h973 = DEF_v__h973;
      }
      ++num;
      if ((backing.DEF_x__h1722) != DEF_x__h1722)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h1722, 32u);
	backing.DEF_x__h1722 = DEF_x__h1722;
      }
      ++num;
      if ((backing.DEF_x__h2279) != DEF_x__h2279)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h2279, 32u);
	backing.DEF_x__h2279 = DEF_x__h2279;
      }
      ++num;
      if ((backing.DEF_x__h426) != DEF_x__h426)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h426, 4u);
	backing.DEF_x__h426 = DEF_x__h426;
      }
      ++num;
      if ((backing.DEF_x_wget__h1219) != DEF_x_wget__h1219)
      {
	vcd_write_val(sim_hdl, num, DEF_x_wget__h1219, 8u);
	backing.DEF_x_wget__h1219 = DEF_x_wget__h1219;
      }
      ++num;
      if ((backing.DEF_x_wget__h842) != DEF_x_wget__h842)
      {
	vcd_write_val(sim_hdl, num, DEF_x_wget__h842, 8u);
	backing.DEF_x_wget__h842 = DEF_x_wget__h842;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_mod_mul_step, 1u);
      backing.DEF_CAN_FIRE_RL_mod_mul_step = DEF_CAN_FIRE_RL_mod_mul_step;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_tb_feed, 1u);
      backing.DEF_CAN_FIRE_RL_tb_feed = DEF_CAN_FIRE_RL_tb_feed;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_tb_monitor_test, 1u);
      backing.DEF_CAN_FIRE_RL_tb_monitor_test = DEF_CAN_FIRE_RL_tb_monitor_test;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_tb_randomA_every, 1u);
      backing.DEF_CAN_FIRE_RL_tb_randomA_every = DEF_CAN_FIRE_RL_tb_randomA_every;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_tb_randomA_every_1, 1u);
      backing.DEF_CAN_FIRE_RL_tb_randomA_every_1 = DEF_CAN_FIRE_RL_tb_randomA_every_1;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_tb_randomB_every, 1u);
      backing.DEF_CAN_FIRE_RL_tb_randomB_every = DEF_CAN_FIRE_RL_tb_randomB_every;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_tb_randomB_every_1, 1u);
      backing.DEF_CAN_FIRE_RL_tb_randomB_every_1 = DEF_CAN_FIRE_RL_tb_randomB_every_1;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_tb_read, 1u);
      backing.DEF_CAN_FIRE_RL_tb_read = DEF_CAN_FIRE_RL_tb_read;
      vcd_write_val(sim_hdl, num++, DEF_IF_tb_randomA_zaz_whas__1_THEN_IF_tb_randomA_z_ETC___d32, 1u);
      backing.DEF_IF_tb_randomA_zaz_whas__1_THEN_IF_tb_randomA_z_ETC___d32 = DEF_IF_tb_randomA_zaz_whas__1_THEN_IF_tb_randomA_z_ETC___d32;
      vcd_write_val(sim_hdl, num++, DEF_IF_tb_randomA_zaz_whas__1_THEN_tb_randomA_zaz__ETC___d23, 8u);
      backing.DEF_IF_tb_randomA_zaz_whas__1_THEN_tb_randomA_zaz__ETC___d23 = DEF_IF_tb_randomA_zaz_whas__1_THEN_tb_randomA_zaz__ETC___d23;
      vcd_write_val(sim_hdl, num++, DEF_IF_tb_randomB_zaz_whas__9_THEN_tb_randomB_zaz__ETC___d33, 1u);
      backing.DEF_IF_tb_randomB_zaz_whas__9_THEN_tb_randomB_zaz__ETC___d33 = DEF_IF_tb_randomB_zaz_whas__9_THEN_tb_randomB_zaz__ETC___d33;
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_mod_mul_step, 1u);
      backing.DEF_WILL_FIRE_RL_mod_mul_step = DEF_WILL_FIRE_RL_mod_mul_step;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_tb_feed, 1u);
      backing.DEF_WILL_FIRE_RL_tb_feed = DEF_WILL_FIRE_RL_tb_feed;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_tb_monitor_test, 1u);
      backing.DEF_WILL_FIRE_RL_tb_monitor_test = DEF_WILL_FIRE_RL_tb_monitor_test;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_tb_randomA_every, 1u);
      backing.DEF_WILL_FIRE_RL_tb_randomA_every = DEF_WILL_FIRE_RL_tb_randomA_every;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_tb_randomA_every_1, 1u);
      backing.DEF_WILL_FIRE_RL_tb_randomA_every_1 = DEF_WILL_FIRE_RL_tb_randomA_every_1;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_tb_randomB_every, 1u);
      backing.DEF_WILL_FIRE_RL_tb_randomB_every = DEF_WILL_FIRE_RL_tb_randomB_every;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_tb_randomB_every_1, 1u);
      backing.DEF_WILL_FIRE_RL_tb_randomB_every_1 = DEF_WILL_FIRE_RL_tb_randomB_every_1;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_tb_read, 1u);
      backing.DEF_WILL_FIRE_RL_tb_read = DEF_WILL_FIRE_RL_tb_read;
      vcd_write_val(sim_hdl, num++, DEF__read__h138, 4u);
      backing.DEF__read__h138 = DEF__read__h138;
      vcd_write_val(sim_hdl, num++, DEF_mod_p__h1825, 17u);
      backing.DEF_mod_p__h1825 = DEF_mod_p__h1825;
      vcd_write_val(sim_hdl, num++, DEF_tb_randomA_zaz_whas____d21, 1u);
      backing.DEF_tb_randomA_zaz_whas____d21 = DEF_tb_randomA_zaz_whas____d21;
      vcd_write_val(sim_hdl, num++, DEF_tb_read_count_6_EQ_128___d57, 1u);
      backing.DEF_tb_read_count_6_EQ_128___d57 = DEF_tb_read_count_6_EQ_128___d57;
      vcd_write_val(sim_hdl, num++, DEF_v__h1276, 32u);
      backing.DEF_v__h1276 = DEF_v__h1276;
      vcd_write_val(sim_hdl, num++, DEF_v__h1349, 8u);
      backing.DEF_v__h1349 = DEF_v__h1349;
      vcd_write_val(sim_hdl, num++, DEF_v__h899, 32u);
      backing.DEF_v__h899 = DEF_v__h899;
      vcd_write_val(sim_hdl, num++, DEF_v__h973, 8u);
      backing.DEF_v__h973 = DEF_v__h973;
      vcd_write_val(sim_hdl, num++, DEF_x__h1722, 32u);
      backing.DEF_x__h1722 = DEF_x__h1722;
      vcd_write_val(sim_hdl, num++, DEF_x__h2279, 32u);
      backing.DEF_x__h2279 = DEF_x__h2279;
      vcd_write_val(sim_hdl, num++, DEF_x__h426, 4u);
      backing.DEF_x__h426 = DEF_x__h426;
      vcd_write_val(sim_hdl, num++, DEF_x_wget__h1219, 8u);
      backing.DEF_x_wget__h1219 = DEF_x_wget__h1219;
      vcd_write_val(sim_hdl, num++, DEF_x_wget__h842, 8u);
      backing.DEF_x_wget__h842 = DEF_x_wget__h842;
    }
}

void MOD_mkTbEx7a::vcd_prims(tVCDDumpType dt, MOD_mkTbEx7a &backing)
{
  INST_mod_i.dump_VCD(dt, backing.INST_mod_i);
  INST_mod_m_neg.dump_VCD(dt, backing.INST_mod_m_neg);
  INST_mod_m_pos.dump_VCD(dt, backing.INST_mod_m_pos);
  INST_mod_p.dump_VCD(dt, backing.INST_mod_p);
  INST_tb_cycle.dump_VCD(dt, backing.INST_tb_cycle);
  INST_tb_feed_count.dump_VCD(dt, backing.INST_tb_feed_count);
  INST_tb_operands_fifo.dump_VCD(dt, backing.INST_tb_operands_fifo);
  INST_tb_randomA_ignore.dump_VCD(dt, backing.INST_tb_randomA_ignore);
  INST_tb_randomA_initialized.dump_VCD(dt, backing.INST_tb_randomA_initialized);
  INST_tb_randomA_zaz.dump_VCD(dt, backing.INST_tb_randomA_zaz);
  INST_tb_randomB_ignore.dump_VCD(dt, backing.INST_tb_randomB_ignore);
  INST_tb_randomB_initialized.dump_VCD(dt, backing.INST_tb_randomB_initialized);
  INST_tb_randomB_zaz.dump_VCD(dt, backing.INST_tb_randomB_zaz);
  INST_tb_read_count.dump_VCD(dt, backing.INST_tb_read_count);
}
